# Candidate Database Configuration
---
apiVersion: platform.xyz.com/v1alpha1
kind: Database
metadata:
  name: candidate-db
  namespace: candidate
  labels:
    app: candidate-db
spec:
  type: postgresql
  version: "15"
  size: small
  storage: "5Gi"
  replicas: 1  # Use 3 for production HA
  backups:
    enabled: true
    schedule: "0 2 * * *"
    retention: "7d"

---
# CloudNativePG Cluster (actual PostgreSQL deployment)
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: candidate-db
  namespace: candidate
  labels:
    app: candidate-db
spec:
  instances: 1  # Use 3 for production HA
  
  imageName: ghcr.io/cloudnative-pg/postgresql:15.4
  
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"
      effective_cache_size: "512MB"
      maintenance_work_mem: "64MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "4MB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"
  
  storage:
    size: 5Gi
    storageClass: ""  # Use default storage class
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  
  # Backup configuration
  backup:
    barmanObjectStore:
      destinationPath: ""  # Set to S3/GCS path for backups
      # s3Credentials:
      #   accessKeyId:
      #     name: backup-creds
      #     key: ACCESS_KEY_ID
      #   secretAccessKey:
      #     name: backup-creds
      #     key: SECRET_ACCESS_KEY
    retentionPolicy: "7d"
  
  # Bootstrap from empty database
  bootstrap:
    initdb:
      database: candidate
      owner: candidate_user
      secret:
        name: candidate-db-credentials

---
# Database credentials secret
apiVersion: v1
kind: Secret
metadata:
  name: candidate-db-credentials
  namespace: candidate
type: kubernetes.io/basic-auth
stringData:
  username: candidate_user
  password: candidate-secure-password-change-me  # Change in production!

