# Hirer Domain Tenant Configuration
---
apiVersion: platform.xyz.com/v1alpha1
kind: Tenant
metadata:
  name: hirer
spec:
  owner: hirer-team
  costCenter: CC-HIRER-001
  quota:
    cpu: "20"
    memory: "40Gi"
    pods: 100
    pvcs: 20
    services: 30
  allowedIntegrations:
    - candidate
    - data-service
    - ai
  contacts:
    slack: "#hirer-platform"
    email: hirer-team@xyz.com

---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: hirer
  labels:
    platform.xyz.com/owner: hirer-team
    platform.xyz.com/tenant: hirer
    platform.xyz.com/cost-center: CC-HIRER-001
    istio-injection: enabled
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

---
# Resource Quota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: hirer
spec:
  hard:
    requests.cpu: "10"
    requests.memory: "20Gi"
    limits.cpu: "20"
    limits.memory: "40Gi"
    pods: "100"
    persistentvolumeclaims: "20"
    services: "30"
    secrets: "50"
    configmaps: "50"

---
# Limit Range
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: hirer
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      max:
        cpu: "4"
        memory: "8Gi"
      min:
        cpu: "50m"
        memory: "64Mi"

---
# Network Policy - Default deny ingress
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: hirer
spec:
  podSelector: {}
  policyTypes:
    - Ingress

---
# Network Policy - Allow same namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-same-namespace
  namespace: hirer
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}

---
# Network Policy - Allow from Istio
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-istio
  namespace: hirer
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system

