# Data Service Domain - API Services
---
apiVersion: platform.xyz.com/v1alpha1
kind: Webservice
metadata:
  name: warehouse-api
  namespace: data-service
  labels:
    app: warehouse-api
    version: v1
spec:
  image: nginx:1.25-alpine
  port: 80
  replicas:
    min: 2
    max: 8
  resources:
    cpu: "500m"
    memory: "1Gi"
  autoscaling:
    enabled: true
    targetCPU: 70
  healthCheck:
    path: /health
    port: 80
  routing:
    public: false
    domain: data.xyz.local
    path: /api/warehouse
  highAvailability: true

---
apiVersion: platform.xyz.com/v1alpha1
kind: Webservice
metadata:
  name: datalake-api
  namespace: data-service
  labels:
    app: datalake-api
    version: v1
spec:
  image: nginx:1.25-alpine
  port: 80
  replicas:
    min: 2
    max: 6
  resources:
    cpu: "500m"
    memory: "1Gi"
  autoscaling:
    enabled: true
    targetCPU: 70
  healthCheck:
    path: /health
    port: 80
  routing:
    public: false
    domain: data.xyz.local
    path: /api/datalake
  highAvailability: true

---
# Manual Deployments (until operator is built)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-api
  namespace: data-service
  labels:
    app: warehouse-api
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: warehouse-api
  template:
    metadata:
      labels:
        app: warehouse-api
        version: v1
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: api
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: warehouse-api
  namespace: data-service
  labels:
    app: warehouse-api
spec:
  selector:
    app: warehouse-api
  ports:
    - name: http
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datalake-api
  namespace: data-service
  labels:
    app: datalake-api
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: datalake-api
  template:
    metadata:
      labels:
        app: datalake-api
        version: v1
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: api
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: datalake-api
  namespace: data-service
  labels:
    app: datalake-api
spec:
  selector:
    app: datalake-api
  ports:
    - name: http
      port: 80
      targetPort: 80

