apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: caches.platform.xyz.com
spec:
  group: platform.xyz.com
  names:
    kind: Cache
    listKind: CacheList
    plural: caches
    singular: cache
    shortNames:
      - ca
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - type
              properties:
                type:
                  type: string
                  description: Cache type
                  enum:
                    - redis
                    - memcached
                  default: redis
                version:
                  type: string
                  description: Cache version
                  default: "7"
                size:
                  type: string
                  description: Instance size
                  enum:
                    - small
                    - medium
                    - large
                  default: small
                persistence:
                  type: boolean
                  description: Enable persistent storage
                  default: false
                storage:
                  type: string
                  description: Storage size if persistence enabled
                  default: "5Gi"
                replicas:
                  type: integer
                  description: Number of replicas
                  default: 1
                  minimum: 1
                  maximum: 6
                maxMemory:
                  type: string
                  description: Maximum memory for cache
                  default: "256mb"
                evictionPolicy:
                  type: string
                  description: Eviction policy when max memory reached
                  enum:
                    - noeviction
                    - allkeys-lru
                    - volatile-lru
                    - allkeys-random
                    - volatile-random
                    - volatile-ttl
                  default: allkeys-lru
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum:
                    - Pending
                    - Creating
                    - Running
                    - Failed
                    - Terminating
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
                connectionSecret:
                  type: string
                  description: Secret containing connection credentials
                host:
                  type: string
                port:
                  type: integer
                readyReplicas:
                  type: integer
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Type
          type: string
          jsonPath: .spec.type
        - name: Version
          type: string
          jsonPath: .spec.version
        - name: Size
          type: string
          jsonPath: .spec.size
        - name: Status
          type: string
          jsonPath: .status.phase
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp

