apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databases.platform.xyz.com
spec:
  group: platform.xyz.com
  names:
    kind: Database
    listKind: DatabaseList
    plural: databases
    singular: database
    shortNames:
      - db
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - type
              properties:
                type:
                  type: string
                  description: Database type
                  enum:
                    - postgresql
                    - mysql
                version:
                  type: string
                  description: Database version
                  default: "15"
                size:
                  type: string
                  description: Instance size (small, medium, large)
                  enum:
                    - small
                    - medium
                    - large
                  default: small
                storage:
                  type: string
                  description: Storage size
                  default: "10Gi"
                replicas:
                  type: integer
                  description: Number of replicas (1 for dev, 3 for HA)
                  default: 1
                  minimum: 1
                  maximum: 5
                backups:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      default: true
                    schedule:
                      type: string
                      default: "0 2 * * *"
                      description: Cron schedule for backups
                    retention:
                      type: string
                      default: "7d"
                      description: How long to keep backups
                    destination:
                      type: string
                      description: S3/GCS bucket for backups
                parameters:
                  type: object
                  additionalProperties:
                    type: string
                  description: Database-specific parameters
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum:
                    - Pending
                    - Creating
                    - Running
                    - Failed
                    - Terminating
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
                connectionSecret:
                  type: string
                  description: Secret containing connection credentials
                host:
                  type: string
                port:
                  type: integer
                readyReplicas:
                  type: integer
                currentVersion:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Type
          type: string
          jsonPath: .spec.type
        - name: Version
          type: string
          jsonPath: .spec.version
        - name: Size
          type: string
          jsonPath: .spec.size
        - name: Status
          type: string
          jsonPath: .status.phase
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp

