apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: domainintegrations.platform.xyz.com
spec:
  group: platform.xyz.com
  names:
    kind: DomainIntegration
    listKind: DomainIntegrationList
    plural: domainintegrations
    singular: domainintegration
    shortNames:
      - di
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - targetDomain
                - targetService
              properties:
                targetDomain:
                  type: string
                  description: The domain (namespace) to integrate with
                targetService:
                  type: string
                  description: The service to connect to in target domain
                targetPort:
                  type: integer
                  description: The port of the target service
                  default: 80
                permissions:
                  type: array
                  description: List of permissions requested
                  items:
                    type: string
                config:
                  type: object
                  properties:
                    timeout:
                      type: string
                      description: Connection timeout
                      default: "5s"
                    retries:
                      type: integer
                      description: Number of retry attempts
                      default: 3
                    circuitBreaker:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                          default: true
                        maxConnections:
                          type: integer
                          default: 100
                        maxPendingRequests:
                          type: integer
                          default: 100
                        maxRetries:
                          type: integer
                          default: 3
                authentication:
                  type: object
                  properties:
                    type:
                      type: string
                      enum:
                        - mtls
                        - jwt
                        - apiKey
                      default: mtls
                    secretRef:
                      type: string
                      description: Secret containing auth credentials
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum:
                    - Pending
                    - Approved
                    - Active
                    - Denied
                    - Failed
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
                approvedBy:
                  type: string
                  description: Who approved this integration
                approvedAt:
                  type: string
                  format: date-time
                networkPolicyCreated:
                  type: boolean
                authorizationPolicyCreated:
                  type: boolean
                serviceEntryCreated:
                  type: boolean
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Target Domain
          type: string
          jsonPath: .spec.targetDomain
        - name: Target Service
          type: string
          jsonPath: .spec.targetService
        - name: Status
          type: string
          jsonPath: .status.phase
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp

