apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scheduledtasks.platform.xyz.com
spec:
  group: platform.xyz.com
  names:
    kind: ScheduledTask
    listKind: ScheduledTaskList
    plural: scheduledtasks
    singular: scheduledtask
    shortNames:
      - st
      - cron
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - schedule
                - image
              properties:
                schedule:
                  type: string
                  description: Cron schedule expression
                image:
                  type: string
                  description: Container image to run
                command:
                  type: array
                  description: Command to execute
                  items:
                    type: string
                args:
                  type: array
                  description: Arguments to the command
                  items:
                    type: string
                resources:
                  type: object
                  properties:
                    cpu:
                      type: string
                      default: "500m"
                    memory:
                      type: string
                      default: "512Mi"
                timeout:
                  type: string
                  description: Maximum duration for the task
                  default: "1h"
                retries:
                  type: integer
                  description: Number of retry attempts on failure
                  default: 3
                  minimum: 0
                  maximum: 10
                concurrencyPolicy:
                  type: string
                  description: How to handle concurrent runs
                  enum:
                    - Allow
                    - Forbid
                    - Replace
                  default: Forbid
                suspend:
                  type: boolean
                  description: Suspend the scheduled task
                  default: false
                successfulJobsHistoryLimit:
                  type: integer
                  default: 3
                failedJobsHistoryLimit:
                  type: integer
                  default: 1
                env:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                      valueFrom:
                        type: object
                        properties:
                          secretKeyRef:
                            type: object
                            properties:
                              name:
                                type: string
                              key:
                                type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum:
                    - Active
                    - Suspended
                    - Failed
                lastScheduleTime:
                  type: string
                  format: date-time
                lastSuccessfulTime:
                  type: string
                  format: date-time
                nextScheduleTime:
                  type: string
                  format: date-time
                active:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Schedule
          type: string
          jsonPath: .spec.schedule
        - name: Suspend
          type: boolean
          jsonPath: .spec.suspend
        - name: Last Schedule
          type: date
          jsonPath: .status.lastScheduleTime
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp

