# ArgoCD Installation
# This file provides customized ArgoCD installation for XYZ Platform
# 
# Quick install:
#   kubectl create namespace argocd
#   kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
#   kubectl apply -f platform/argocd/

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # URL of ArgoCD server
  url: https://argocd.localhost

  # Dex configuration for SSO
  dex.config: |
    connectors:
      - type: oidc
        id: dex
        name: Platform SSO
        config:
          issuer: http://dex.dex.svc.cluster.local:5556
          clientID: argocd
          clientSecret: $dex.clientSecret
          insecureEnableGroups: true
          scopes:
            - openid
            - profile
            - email
            - groups

  # Repository credentials template
  repository.credentials: |
    - url: https://github.com/xyz-company
      passwordSecret:
        name: github-creds
        key: password
      usernameSecret:
        name: github-creds
        key: username

  # Resource customizations
  resource.customizations: |
    platform.xyz.com/Tenant:
      health.lua: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.phase == "Active" then
            hs.status = "Healthy"
            hs.message = "Tenant is active"
          elseif obj.status.phase == "Pending" then
            hs.status = "Progressing"
            hs.message = "Tenant is being created"
          elseif obj.status.phase == "Failed" then
            hs.status = "Degraded"
            hs.message = obj.status.conditions[1].message
          else
            hs.status = "Unknown"
          end
        end
        return hs
    platform.xyz.com/Webservice:
      health.lua: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.phase == "Running" then
            hs.status = "Healthy"
            hs.message = "Webservice is running"
          elseif obj.status.phase == "Deploying" then
            hs.status = "Progressing"
            hs.message = "Webservice is deploying"
          elseif obj.status.phase == "Failed" then
            hs.status = "Degraded"
            hs.message = "Webservice failed"
          else
            hs.status = "Unknown"
          end
        end
        return hs

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    # Platform admins have full access
    p, role:platform-admin, applications, *, */*, allow
    p, role:platform-admin, clusters, *, *, allow
    p, role:platform-admin, repositories, *, *, allow
    p, role:platform-admin, projects, *, *, allow

    # Tenant developers can manage their own applications
    p, role:candidate-developer, applications, *, candidate/*, allow
    p, role:candidate-developer, applications, sync, candidate/*, allow
    p, role:candidate-developer, logs, get, candidate/*, allow

    p, role:hirer-developer, applications, *, hirer/*, allow
    p, role:hirer-developer, applications, sync, hirer/*, allow
    p, role:hirer-developer, logs, get, hirer/*, allow

    p, role:sales-developer, applications, *, sales/*, allow
    p, role:sales-developer, applications, sync, sales/*, allow
    p, role:sales-developer, logs, get, sales/*, allow

    p, role:marketing-developer, applications, *, marketing/*, allow
    p, role:marketing-developer, applications, sync, marketing/*, allow
    p, role:marketing-developer, logs, get, marketing/*, allow

    p, role:operations-developer, applications, *, operations/*, allow
    p, role:operations-developer, applications, sync, operations/*, allow
    p, role:operations-developer, logs, get, operations/*, allow

    p, role:data-developer, applications, *, data-service/*, allow
    p, role:data-developer, applications, sync, data-service/*, allow
    p, role:data-developer, logs, get, data-service/*, allow

    p, role:ai-developer, applications, *, ai/*, allow
    p, role:ai-developer, applications, sync, ai/*, allow
    p, role:ai-developer, logs, get, ai/*, allow

    p, role:analytics-developer, applications, *, analytics/*, allow
    p, role:analytics-developer, applications, sync, analytics/*, allow
    p, role:analytics-developer, logs, get, analytics/*, allow

    # Map groups to roles (from Dex/Okta)
    g, platform-admins, role:platform-admin
    g, candidate-team, role:candidate-developer
    g, hirer-team, role:hirer-developer
    g, sales-team, role:sales-developer
    g, marketing-team, role:marketing-developer
    g, operations-team, role:operations-developer
    g, data-team, role:data-developer
    g, ai-team, role:ai-developer
    g, analytics-team, role:analytics-developer

    # Map individual users for demo
    g, admin@xyz.local, role:platform-admin
    g, john.doe@xyz.local, role:candidate-developer
    g, jane.smith@xyz.local, role:hirer-developer
    g, bob.ml@xyz.local, role:ai-developer

  scopes: '[groups, email]'

---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  # Dex client secret
  dex.clientSecret: "argocd-dex-secret"

