# AI Domain - Services
---
apiVersion: platform.xyz.com/v1alpha1
kind: Webservice
metadata:
  name: prediction-api
  namespace: ai
  labels:
    app: prediction-api
    version: v1
spec:
  image: nginx:1.25-alpine
  port: 80
  replicas:
    min: 2
    max: 6
  resources:
    cpu: "1"
    memory: "2Gi"
  autoscaling:
    enabled: true
    targetCPU: 70
  healthCheck:
    path: /health
    port: 80
  routing:
    public: false
    domain: ai.xyz.local
    path: /api/predict
  highAvailability: true

---
# Manual Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-api
  namespace: ai
  labels:
    app: prediction-api
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prediction-api
  template:
    metadata:
      labels:
        app: prediction-api
        version: v1
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: api
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: prediction-api
  namespace: ai
  labels:
    app: prediction-api
spec:
  selector:
    app: prediction-api
  ports:
    - name: http
      port: 80
      targetPort: 80

